# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'steelVis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication


class Ui_MainWindow(object):

    def __init__(self):
        # super().__init__()
        # 默认显示所有表格，同时保存状态
        pass

    def setupUi(self, MainWindow):
        desktop = QApplication.desktop()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1000)
        MainWindow.move(desktop.width() * 0.1, desktop.height() * 0.1)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        ###################################################################
        self.change_time_view = QtWidgets.QSplitter(self.centralwidget)
        self.change_time_view.setGeometry(QtCore.QRect(505, 10, 450, 35))
        self.change_time_view.setOrientation(QtCore.Qt.Horizontal)
        self.change_time_view.setObjectName("change_time_view")
        self.dayButton = QtWidgets.QPushButton(self.change_time_view)
        self.dayButton.setStyleSheet("background-color: rgb(95, 147, 154);")
        self.dayButton.setObjectName("dayButton")
        self.weekButton = QtWidgets.QPushButton(self.change_time_view)
        self.weekButton.setStyleSheet("background-color: rgb(95, 147, 154);")
        self.weekButton.setObjectName("weekButton")
        self.monthButton = QtWidgets.QPushButton(self.change_time_view)
        self.monthButton.setStyleSheet("background-color: rgb(95, 147, 154);")
        self.monthButton.setObjectName("monthButton")
        self.yearButton = QtWidgets.QPushButton(self.change_time_view)
        self.yearButton.setStyleSheet("background-color: rgb(95, 147, 154);")
        self.yearButton.setObjectName("yearButton")

        ###################################################################
        self.change_category = QtWidgets.QSplitter(self.centralwidget)
        self.change_category.setGeometry(QtCore.QRect(10, 250, 91, 501))
        self.change_category.setOrientation(QtCore.Qt.Vertical)
        self.change_category.setObjectName("change_category")
        self.mainPageButton = QtWidgets.QPushButton(self.change_category)
        self.mainPageButton.setStyleSheet("background-color: rgb(164, 93, 93);")
        self.mainPageButton.setObjectName("mainPageButton")

        self.aluminaButton = QtWidgets.QPushButton(self.change_category)
        self.aluminaButton.setStyleSheet("background-color: rgb(204, 155, 110);")
        self.aluminaButton.setObjectName("aluminaButton")

        self.SMMA00Button = QtWidgets.QPushButton(self.change_category)
        self.SMMA00Button.setStyleSheet("background-color: rgb(204, 155, 110);")
        self.SMMA00Button.setObjectName("SMMA00Button")

        self.rebarButton = QtWidgets.QPushButton(self.change_category)
        self.rebarButton.setStyleSheet("background-color: rgb(204, 155, 110);")
        self.rebarButton.setObjectName("rebarButton")

        self.silicomanganeseButton = QtWidgets.QPushButton(self.change_category)
        self.silicomanganeseButton.setStyleSheet("background-color: rgb(204, 155, 110);")
        self.silicomanganeseButton.setObjectName("silicomanganeseButton")

        self.eleManganeseButton = QtWidgets.QPushButton(self.change_category)
        self.eleManganeseButton.setStyleSheet("background-color: rgb(204, 155, 110);")
        self.eleManganeseButton.setObjectName("eleManganeseButton")

        self.thermalCoalButton = QtWidgets.QPushButton(self.change_category)
        self.thermalCoalButton.setStyleSheet("background-color: rgb(204, 155, 110);")
        self.thermalCoalButton.setObjectName("thermalCoalButton")


        self.eleCopperButton = QtWidgets.QPushButton(self.change_category)
        self.eleCopperButton.setStyleSheet("background-color: rgb(204, 155, 110);")
        self.eleCopperButton.setObjectName("eleCopperButton")

        self.SMMaluminaButton = QtWidgets.QPushButton(self.change_category)
        self.SMMaluminaButton.setStyleSheet("background-color: rgb(204, 155, 110);")
        self.SMMaluminaButton.setObjectName("SMMaluminaButton")

        ###################################################################
        self.toolBoxs = QtWidgets.QSplitter(self.centralwidget)
        self.toolBoxs.setGeometry(QtCore.QRect(450, 50, 571, 31))
        self.toolBoxs.setStyleSheet("")
        self.toolBoxs.setOrientation(QtCore.Qt.Horizontal)
        self.toolBoxs.setObjectName("toolBoxs")
        self.regular_update = QtWidgets.QPushButton(self.toolBoxs)
        self.regular_update.setStyleSheet("background-color: rgb(136, 158, 175);")
        self.regular_update.setObjectName("regular_update")
        self.click_update = QtWidgets.QPushButton(self.toolBoxs)
        self.click_update.setStyleSheet("background-color: rgb(136, 158, 175);")
        self.click_update.setObjectName("click_update")
        self.insert_report = QtWidgets.QPushButton(self.toolBoxs)
        self.insert_report.setStyleSheet("background-color: rgb(136, 158, 175);")
        self.insert_report.setObjectName("insert_report")
        self.predict = QtWidgets.QPushButton(self.toolBoxs)
        self.predict.setStyleSheet("background-color: rgb(136, 158, 175);")
        self.predict.setObjectName("predict")
        ###################################################################
        # 添加一个widget容器，和一个groupBox存放图表
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setGeometry(QtCore.QRect(160, 280, 1200, 700))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 1200, 700))
        self.groupBox.setObjectName("groupBox")
        ####################################################################
        self.label_widget = QtWidgets.QWidget(MainWindow)
        self.label_widget.setGeometry(QtCore.QRect(400, 240, 600, 40))
        self.label_widget.setObjectName("label_widget")

        self.label_groupBox = QtWidgets.QGroupBox(self.label_widget)
        self.label_groupBox.setGeometry(QtCore.QRect(0, 0, 600, 40))
        self.label_groupBox.setObjectName("label_groupBox")


        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1744, 23))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "重点工业产品市场分析预测工具"))
        self.dayButton.setText(_translate("MainWindow", "日"))
        self.weekButton.setText(_translate("MainWindow", " 周"))
        self.monthButton.setText(_translate("MainWindow", "月"))
        self.yearButton.setText(_translate("MainWindow", "年"))
        self.mainPageButton.setText(_translate("MainWindow", "总页面"))
        self.rebarButton.setText(_translate("MainWindow", "螺纹钢"))
        self.eleCopperButton.setText(_translate("MainWindow", "电解铜"))
        self.aluminaButton.setText(_translate("MainWindow", "氧化铝"))
        self.silicomanganeseButton.setText(_translate("MainWindow", "硅锰"))
        self.thermalCoalButton.setText(_translate("MainWindow", "动力煤"))
        self.SMMA00Button.setText(_translate("MainWindow", "电解铝"))
        self.SMMaluminaButton.setText(_translate("MainWindow", "SMM氧化铝"))
        self.eleManganeseButton.setText(_translate("MainWindow", "电解锰"))
        self.regular_update.setText(_translate("MainWindow", "定时更新"))
        self.click_update.setText(_translate("MainWindow", "点击更新"))
        self.insert_report.setText(_translate("MainWindow", "一键插入报告"))
        self.predict.setText(_translate("MainWindow", "预测"))
        self.groupBox.setTitle(_translate("MainWindow", "价格曲线图："))

































